### ISSUE TITLE
Syntax error on Firefox 84.0

### ISSUE THREAD

**Issue by thorphil** [danchitnis/EEsim#9]
Pressing run button on loading page causes page to hang.  Debugger gives following error:

SyntaxError: import declarations may only appear at top level of a module - simulationLink.js:1

**Comment by danchitnis** [comment]
It a new feature related to module imports in web workers [(status here)](https://www.chromestatus.com/feature/5761300827209728). Firefox and Safari haven't implemented it yet. I will see if there is a workaround.

**Comment by danchitnis** [comment]
Working now on Firefox 111.0
